import fetch from 'isomorphic-unfetch'

import VideosScreen from '@global-modules/videos/screen/main'
import Head from 'next/head'
import { Videos as VideosTypes } from '@global-entities/vidoes'

export async function getStaticProps() {
  try {
    const BASE_URL = process.env.BASE_URL || `https://www.jeftar.com.br/api`
    const res = await fetch(`${BASE_URL}/youtube/videos`, {
      method: 'GET'
    })

    if (!res.ok) {
      return {
        props: {
          channelVideos: {}
        }
      }
    }

    const channelVideos = await res.json()

    return {
      props: {
        channelVideos
      }
    }
  } catch (error) {
    return {
      props: {
        channelVideos: {}
      }
    }
  }
}

export default function Videos({
  channelVideos
}: {
  channelVideos: VideosTypes
}) {
  return (
    <>
      <Head>
        <title>Jeftar Mascarenhas - Vídeos Free</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VideosScreen channelVideos={channelVideos} />
    </>
  )
}
