import fetch from 'isomorphic-unfetch'

import VideosScreen from '@global-modules/videos/screen/main'
import Head from 'next/head'
import { Videos as VideosTypes } from '@global-entities/vidoes'

export async function getStaticProps() {
  const res = await fetch('https://jeftar.com.br/api/youtube/videos', {
    method: 'GET'
  })

  const channelVideos = await res.json()

  return {
    props: {
      channelVideos
    }
  }
}

export default function Videos({
  channelVideos
}: {
  channelVideos: VideosTypes
}) {
  return (
    <>
      <Head>
        <title>Jeftar Mascarenhas - Vídeos Free</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VideosScreen channelVideos={channelVideos} />
    </>
  )
}
