import VideosScreen from '@global-modules/videos/screen/main'
import Head from 'next/head'

export default function Videos() {
  return (
    <>
      <Head>
        <title>Jeftar Mascarenhas - Vídeos Free</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VideosScreen />
    </>
  )
}
