backend:
  name: github
  repo: jeftarmascarenhas/jeftarmascarenhas.io
  branch: master

media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: date, label: Date, widget: date, format: YYYY-MM-DD hh:mm:ss }
      - { name: title, label: Title }
      - { label: Cover, name: image, widget: image, required: false }
      - { name: description, label: Description, widget: string }
      - { name: tags, label: Tags, widget: list, default: [''] }
      - { name: body, label: Body, widget: markdown }
