import React from 'react'
import WorkJournalScreen from '@global-modules/work-journal/screens/main'
import Head from 'next/head'

export default function WorkJournal() {
  return (
    <div>
      <Head>
        <title>Jeftar Mascarenhas - Work Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WorkJournalScreen />
    </div>
  )
}
