import CourseScreen from 'modules/courses/screens/main'
import Head from 'next/head'

export default function Course() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CourseScreen />
    </div>
  )
}
